### ISSUE TITLE
need to fix pcl_macro.h

### ISSUE THREAD

**Issue by k-okada** [patmarion/pcl-superbuild#9]
I need to fix pcl_macros.h to compile on Ubuntu12.04

```
#elif ANDROID
// Use the math.h macros                                                       
# include <cmath>
# define pcl_isnan(x)    std::isnan(x)
# define pcl_isfinite(x) std::isfinite(x)
```

```
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/io.cpp.o
In file included from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/pcl/common/include/pcl/point_types.h:301:0,
                 from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/pcl/common/src/io.cpp:40:
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/pcl/common/include/pcl/impl/point_types.hpp:1009:68: warning: 'SHOT' is deprecated [-Wdeprecated-declarations]
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/pcl/common/include/pcl/impl/point_types.hpp: In function 'bool pcl::isFinite(const PointT&) [with PointT = pcl::Normal]':
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/pcl/common/include/pcl/impl/point_types.hpp:1318:13: error: 'isfinite' was not declared in this scope
```
