### ISSUE TITLE
Threading support unavaliable error 

### ISSUE THREAD

**Issue by k-okada** [patmarion/pcl-superbuild#8]
This is just a report, I have compile error on pcl-superbuild on my Ubutnu 12.04 machine and fixed by following instructions -> ttp://stackoverflow.com/questions/5389853/doesnt-compile-if-included-boost-thread-in-linux-ubuntu10-10

```
-- Build files have been written to: /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Build/boost-android
[ 12%] Performing forcebuild step for 'boost-android'
[ 13%] Performing build step for 'boost-android'
[ 10%] Built target boost_date_time
[ 16%] Built target boost_filesystem
[ 25%] Built target boost_iostreams
[ 47%] Built target boost_program_options
[ 83%] Built target boost_regex
[ 93%] Built target boost_signals
[ 95%] Built target boost_system
[ 97%] Building CXX object CMakeFiles/boost_thread.dir/boost_1_45_0/libs/thread/src/pthread/thread.cpp.o
In file included from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/thread/detail/platform.hpp:17:0,
                 from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/thread/detail/config.hpp:20,
                 from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/libs/thread/src/pthread/thread.cpp:8:
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/config/requires_threads.hpp:29:4: error: #error "Threading support unavaliable: it has been explicitly disabled with BOOST_DISABLE_THREADS"
In file included from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/thread/detail/config.hpp:20:0,
                 from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/libs/thread/src/pthread/thread.cpp:8:
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/thread/detail/platform.hpp:67:9: error: #error "Sorry, no boost threads are available for this platform."
In file included from /home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/libs/thread/src/pthread/thread.cpp:10:0:
/home/k-okada/work/pcl-superbuild/build/CMakeExternals/Source/boost/boost_1_45_0/boost/thread/thread.hpp:19:2: error: #error "Boost threads unavailable on this platform"
```
